---

- name: merge nginx configuration between defaults and custom
  when:
    - not running_in_check_mode
  ansible.builtin.set_fact:
    nginx_global: "{{ nginx_defaults_global | combine(nginx_global, recursive=True) }}"
    nginx_http: "{{ nginx_defaults_http | combine(nginx_http, recursive=True) }}"
    nginx_events: "{{ nginx_defaults_events | combine(nginx_events, recursive=True) }}"
    nginx_gzip: "{{ nginx_defaults_gzip | combine(nginx_gzip, recursive=True) }}"
    nginx_ssl: "{{ nginx_defaults_ssl | combine(nginx_ssl, recursive=True) }}"
    nginx_logformat: "{{ nginx_defaults_logformat | combine(nginx_logformat, recursive=True) }}"
    nginx_acme: "{{ nginx_defaults_acme | combine(nginx_acme, recursive=True) }}"
    nginx_custom_includes: "{{ nginx_defaults_custom_includes | combine(nginx_custom_includes, recursive=True) }}"
    nginx_upstreams: "{{ nginx_upstreams | upstreams(nginx_vhosts) }}"
  no_log: true

- name: resolve account data from explicit user
  when:
    - not running_in_check_mode
  bodsch.core.account_defaults:
    user: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
  register: account_result

- name: apply resolved values
  when:
    - not running_in_check_mode
  ansible.builtin.set_fact:
    nginx_user: "{{ account_result.user }}"
    nginx_group: "{{ account_result.group }}"

- name: create nginx cache directories
  when:
    - not running_in_check_mode
  bodsch.core.directories:
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "0750"
    paths: "{{ nginx_http.proxy.cache_path | default([]) | cache_directory }}"

- name: create nginx cache directories
  when:
    - not running_in_check_mode
  bodsch.core.directories:
    base_path: /etc/nginx
    owner: root
    group: root
    mode: "0750"
    paths:
      - path: sites-available
      - path: sites-enabled
      - path: includes.d
      - path: conf.d

- name: remove default site
  when:
    - not running_in_check_mode
    - nginx_default_site.remove | default('true')
  ansible.builtin.file:
    name: "{{ nginx_default_site.file | default('/etc/nginx/sites-enabled/default') }}"
    state: absent

- name: acme challenge
  when:
    - not running_in_check_mode
    - nginx_acme is defined
    - nginx_acme.enabled
    - nginx_acme.challenge_directory is defined
    - nginx_acme.challenge_directory | length > 0
  block:
    - name: create acme challenge directory
      ansible.builtin.file:
        path: "{{ nginx_acme.challenge_directory }}/.well-known/acme-challenge"
        state: directory
        owner: "{{ nginx_user }}"
        group: "{{ nginx_group }}"
        mode: "0755"

    - name: fix directory rights for {{ nginx_acme.challenge_directory }}
      ansible.builtin.file:
        path: "{{ nginx_acme.challenge_directory }}"
        state: directory
        owner: "{{ nginx_user }}"
        group: "{{ nginx_group }}"
        mode: "0755"
        recurse: true

- name: create conf.d/gzip.conf
  when:
    - not running_in_check_mode
  ansible.builtin.include_tasks: configure/gzip.yml

- name: create conf.d/upstreams.conf
  when:
    - not running_in_check_mode
  ansible.builtin.include_tasks: configure/upstreams.yml

- name: create ssl configuration files
  when:
    - not running_in_check_mode
  ansible.builtin.include_tasks: configure/ssl.yml

- name: create includes.d/nginx_log.conf
  when:
    - not running_in_check_mode
  ansible.builtin.include_tasks: configure/log.yml

- name: configure geoip
  when:
    - not running_in_check_mode
  ansible.builtin.include_tasks: configure/geoip.yml

- name: create includes.d/useragent.rules
  when:
    - not running_in_check_mode
  ansible.builtin.include_tasks: configure/useragent_rules.yml

- name: create includes.d/proxy.rules
  when:
    - not running_in_check_mode
  ansible.builtin.include_tasks: configure/proxy_rules.yml

- name: create includes.d/global.rules
  when:
    - not running_in_check_mode
  ansible.builtin.include_tasks: configure/global_rules.yml

- name: create includes.d/limits.rules
  when:
    - not running_in_check_mode
  ansible.builtin.include_tasks: configure/limit_rules.yml

- name: create custom includes
  become: true
  when:
    - not running_in_check_mode
  ansible.builtin.template:
    src: includes.d/custom_include.j2
    dest: /etc/nginx/includes.d/{{ item.key }}
    mode: "0644"
  loop:
    "{{ nginx_custom_includes | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  notify:
    - validate nginx config
    - reload nginx

- name: create nginx main configuration
  when:
    - not running_in_check_mode
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: "{{ nginx_group }}"
    mode: "0644"
    backup: true
  notify:
    - validate nginx config
    - reload nginx

...
