---

- name: install nginx
  ansible.builtin.package:
    name: "{{ nginx_packages }}"
    state: present

- name: nginx version
  nginx_version:
  register: _nginx_version

- name: define nginx version
  ansible.builtin.set_fact:
    nginx_version: "{{ _nginx_version.version }}"

- name: extra modules
  when:
    - nginx_extra_modules | default([]) | count > 0
  block:
#     - name: verify extra modules
#
#
#
    - name: install extra modules
      ansible.builtin.package:
        name: "{{ nginx_extra_modules }}"
        state: present
...
