---

- name: restart nginx if needed
  ansible.builtin.meta: flush_handlers

- name: ensure nginx is enabled on boot
  become: true
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started

...
