---

- name: validate nginx config
  nginx_verify_config:
  register: _validate
  changed_when: _validate.rc != 0
  failed_when: _validate.rc != 0

- name: restart nginx if needed
  ansible.builtin.meta: flush_handlers

- name: ensure nginx is enabled on boot
  become: true
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started

...
