---

- name: create HTTP vhost configurations
  ansible.builtin.template:
    src: "{{ item.value.template | default( 'vhosts/' ~ nginx_vhost_templates.http ) }}"
    dest: "/etc/nginx/sites-available/{{ item.value.filename | default( item.key ~ '.conf' ) }}"
    force: true
    owner: root
    group: root
    mode: 0644
  when:
    - item.value.state | default('present') == 'present'
  register: _created_vhost_http
  loop:
    "{{ nginx_http_vhosts | dict2items }}"
  loop_control:
    label: "{{ item.value.filename | default( item.key ~ '.conf') }}"

- name: create HTTPs vhost configurations
  ansible.builtin.template:
    src: "{{ item.value.template | default( 'vhosts/' ~ nginx_vhost_templates.https ) }}"
    dest: "/etc/nginx/sites-available/{{ item.value.filename | default( item.key ~ '.conf' ) }}"
    force: true
    owner: root
    group: root
    mode: 0644
  when:
    - item.value.state | default('present') == 'present'
  register: _created_vhost_https
  loop:
    "{{ nginx_https_vhosts | dict2items }}"
  loop_control:
    label: "{{ item.value.filename | default( item.key ~ '.conf') }}"

- name: changed vhosts
  ansible.builtin.set_fact:
    _nginx_changed_vhosts: "{{ 'true'
        if
          _created_vhost_http | changed_vhosts or
          _created_vhost_https | changed_vhosts
        else
          'false'
    }}"

- name: trigger handler when vhosts configurations have been changed
  ansible.builtin.debug:
    msg: "{{ _nginx_changed_vhosts | bool }}"
  changed_when: "_nginx_changed_vhosts | default('false') | bool"
  notify:
    - validate config
    - reload service

# ---------------------------------------------------------------------------------------

- name: enable HTTP sites configs
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ item.value.filename | default( item.key ~ '.conf') }}
    dest: /etc/nginx/sites-enabled/{{ item.value.filename | default( item.key ~ '.conf') }}
    state: link
    force: true
  loop:
    "{{ nginx_http_vhosts | dict2items }}"
  loop_control:
    label: "{{ item.value.filename | default( item.key ~ '.conf') }}"
  when:
    - item.value.state | default('present') == 'present'
    - item.value.enabled | default('true')
    - not ansible_check_mode
  notify:
    - validate config
    - reload service

# ---------------------------------------------------------------------------------------

- name: enable HTTPs sites configs with existing certificates
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ item.value.filename | default( item.key ~ '.conf') }}
    dest: /etc/nginx/sites-enabled/{{ item.value.filename | default( item.key ~ '.conf') }}
    state: link
    force: true
  loop:
    "{{ nginx_https_vhosts | dict2items }}"
  loop_control:
    label: "{{ item.value.filename | default( item.key ~ '.conf') }}"
  when:
    - item.value.state | default('present') == 'present'
    - item.value.enabled | default('true')
    - item.value.ssl.state | default('missing') == 'present'
    - not ansible_check_mode
  notify:
    - validate config
    - reload service

# ---------------------------------------------------------------------------------------

...
