---

- name: create HTTP vhost configurations
  template:
    src: "{{ item.value.template | default( 'vhosts/' ~ nginx_vhost_templates.http ) }}"
    dest: "/etc/nginx/sites-available/{{ item.value.filename | default( item.key ~ '.conf' ) }}"
    force: true
    owner: root
    group: root
    mode: 0644
  when:
    - item | create_vhost('http')
  loop:
    "{{ nginx_vhosts | dict2items }}"
  loop_control:
    label: "{{ item.value.filename | default( item.key ~ '.conf') }}"
  # notify: reload nginx

- name: create HTTPs vhost configurations without ACME certificates
  template:
    src: "{{ item.value.template | default( 'vhosts/' ~ nginx_vhost_templates.https ) }}"
    dest: "/etc/nginx/sites-available/{{ item.value.filename | default( item.key ~ '.conf' ) }}"
    force: true
    owner: root
    group: root
    mode: 0644
  when:
    - item | create_vhost('https')
  loop:
    "{{ nginx_vhosts | dict2items }}"
  loop_control:
    label: "{{ item.value.filename | default( item.key ~ '.conf') }}"
  # notify: reload nginx

# ---------------------------------------------------------------------------------------

- name: -> enable site config without enabled letsencrypt certificate
  debug:
    msg: "{{ item.key }}"
  when:
    - item | create_vhost('https')
    - item | active_vhost(
        certificate_exists=item.value.ssl_certificate_exists | default('false') | bool )
  loop:
    "{{ nginx_vhosts | dict2items }}"
  loop_control:
    label: "{{ item.value.filename | default( item.key ~ '.conf') }}"


- name: enable site config without enabled letsencrypt certificate
  file:
    src: /etc/nginx/sites-available/{{ item.value.filename | default( item.key ~ '.conf') }}
    dest: /etc/nginx/sites-enabled/{{ item.value.filename | default( item.key ~ '.conf') }}
    state: link
  loop:
    "{{ nginx_vhosts | dict2items }}"
  loop_control:
    label: "{{ item.value.filename | default( item.key ~ '.conf') }}"
  when:
    - item | create_vhost('https')
    - item | active_vhost(
        certificate_exists=item.value.ssl_certificate_exists | default('false') | bool )
    - not ansible_check_mode
  # notify: Reload Nginx

...
