---

- name: create HTTP vhost configurations
  nginx_vhosts:
    vhosts: "{{ nginx_vhosts_http }}"
    template:
      path: "{{ nginx_remote_tmp_directory }}/{{ ansible_fqdn }}"
      http: "{{ nginx_vhost_templates.http }}"
      https: "{{ nginx_vhost_templates.https }}"
    # acme: "{{ nginx_acme }}"
  notify:
    - validate config
    - reload nginx

- name: create HTTPs vhost configurations
  nginx_vhosts:
    vhosts: "{{ nginx_vhosts_https }}"
    template:
      path: "{{ nginx_remote_tmp_directory }}/{{ ansible_fqdn }}"
      http: "{{ nginx_vhost_templates.http }}"
      https: "{{ nginx_vhost_templates.https }}"
    acme: "{{ nginx_acme }}"
  notify:
    - validate config
    - reload nginx

...
