---

- name: validate variables
  ansible.builtin.fail:
    msg: "'nginx_vhosts' should be a list!\nPlease update your configuration."
  when:
    - nginx_vhosts | bodsch.core.type != "list"

- name: define vhosts variables
  ansible.builtin.set_fact:
    nginx_vhosts_root_directories: "{{ nginx_vhosts | vhost_directory(directory='root_directory', state='present') }}"
    nginx_vhosts_http: "{{ nginx_vhosts | http_vhosts(tls=False) }}"
    nginx_vhosts_https: "{{ nginx_vhosts | http_vhosts(tls=True) }}"

- name: ensure vhosts root path exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nginx_user }}"
    mode: 0750
  loop:
    "{{ nginx_vhosts_root_directories }}"
  loop_control:
    label: "{{ item }}"

- name: ensure vhosts log path exists
  nginx_log_directories:
    vhosts: "{{ nginx_vhosts }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "0750"
  when:
    - nginx_vhosts is defined

- name: checking existing domains certificates
  nginx_tls_certificates:
    vhosts: "{{ nginx_vhosts_https }}"
  when:
    - nginx_vhosts is defined
  register: check_domain_cert

- name: re-define nginx_vhosts_https with certificates state
  ansible.builtin.set_fact:
    nginx_vhosts_https: "{{ check_domain_cert.https_vhosts }}"

...
