---

- name: define vhosts variables
  set_fact:
    nginx_vhosts_root_directories: "{{ nginx_vhosts | dict2items | vhost_directory('root') }}"
    nginx_http_vhosts: "{{ nginx_vhosts | http_vhosts }}"
    nginx_https_vhosts: "{{ nginx_vhosts | https_vhosts }}"

- name: ensure vhosts root path exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nginx_user }}"
    mode: 0750
  when:
    - item.value.state | default('present') != 'absent'
  loop:
    "{{ nginx_vhosts_root_directories }}"
  loop_control:
    label: "{{ item }}"

- name: ensure vhosts log path exists
  nginx_log_directories:
    vhosts: "{{ nginx_vhosts }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "0750"
  when:
    - nginx_vhosts is defined

- name: checking existing domains certificates
  nginx_tls_certificates:
    vhosts: "{{ nginx_vhosts }}"
  when:
    - nginx_vhosts is defined
  register: check_domain_cert

- name: append certificates state to https vhost configurations
  set_fact:
    nginx_https_vhosts: "{{ nginx_https_vhosts | append_certificate_state( check_domain_cert ) }}"

...
