---

- name: de-activate vhosts
  file:
    path: "/etc/nginx/sites-enabled/{{ item.value.filename | default( item.key ~ '.conf' ) }}"
    state: absent
  loop:
    "{{ nginx_vhosts | dict2items }}"
  loop_control:
    label: "{{ item.value.filename | default( item.key ~ '.conf') }}"
  # notify: reload Nginx
  when:
    - not item.value.enabled | default('true')
    # - nginx_de_activate_sites

- name: remove vhost configurations
  file:
    path: "/etc/nginx/sites-available/{{ item.value.filename | default( item.key ~ '.conf' ) }}"
    state: absent
  when:
    - item.value.state | default('present') == 'absent'
  loop:
    "{{ nginx_vhosts | dict2items }}"
  loop_control:
    label: "{{ item.value.filename | default( item.key ~ '.conf') }}"

# TODO remove log directory, or logfile

...
