---

- name: de-activate vhosts
  nginx_site_handler:
    enabled: false
    vhosts: "{{ nginx_vhosts }}"
  register: _deactivated_vhost

- name: remove vhost configurations
  nginx_site_handler:
    state: absent
    vhosts: "{{ nginx_vhosts }}"
  register: _removed_vhost

- name: de-activated vhosts
  debug:
    msg: "{{ _deactivated_vhost }}"
  when:
    - _deactivated_vhost.changed

- name: removed vhost
  debug:
    msg: "{{ _removed_vhost }}"
  when:
    - _removed_vhost.changed

# TODO remove log directory, or logfile

...
