---

- name: de-activate vhosts
  nginx_site_handler:
    enabled: false
    vhosts: "{{ nginx_vhosts }}"
  register: _deactivated_vhost
  notify:
    - de-activated vhosts
    - validate config
    - reload nginx

- name: remove vhost configurations
  nginx_site_handler:
    state: absent
    vhosts: "{{ nginx_vhosts }}"
  register: _removed_vhost
  notify:
    - removed vhost
    - validate config
    - reload nginx

# TODO remove log directory, or logfile

...
