---

nginx_upstreams:
  - name: grafana
    # description: upstream  to local grafana
    servers:
      - 127.0.0.1:3000
  - name: prometheus
    # description: upstream  to local prometheus
    servers:
      - 127.0.0.1:9090

nginx_vhosts:

  - name: default
    description: |
      simply a default vhost
    ssl:
      enabled: false

  - name: nginx-status
    filename: 00-status.conf
    # template: vhost_status.j2
    state: present  # default: present
    enabled: true   # default: true
    # domain(s)
    domains:
      - localhost
    # listen
    listen:
      - 127.0.0.1:8088

    root_directory: /var/www/

    # locations
    locations:
      "/nginx_status":
        options: |
          stub_status on;
          access_log off;
          allow 127.0.0.1;
          deny all;

  - name: monitoring.molecule.lan
    filename: 10-monitoring.molecule.lan.conf
    state: present
    enabled: false

    domains:
      - monitoring.molecule.lan

    listen: 80

    upstreams:
      - name: grafana
        servers:
          - 127.0.0.1:3000
      - name: prometheus
        servers:
          - 127.0.0.1:9090

    root_directory: /var/www/monitoring.molecule.lan
    root_directory_create: true

    logfiles:
      access:
        file: /var/log/nginx/monitoring.molecule.lan/access.log
        loglevel: 'json_full if=$excluded_ua'
      error:
        file: /var/log/nginx/monitoring.molecule.lan/error.log
        loglevel: notice

  - name: foo.molecule.lan
    filename: 15-foo.molecule.lan.conf
    state: present
    enabled: true

    domains:
      - foo.molecule.lan

    # Specify which port you want to listen to with clear HTTP, or leave undefined for 80
    listen:
      - 9443

    # enable ssl
    ssl:
      enabled: true
      ciphers: default
      certificate: /etc/snakeoil/molecule.lan/molecule.lan.pem
      certificate_key: /etc/snakeoil/molecule.lan/molecule.lan.key
      dhparam: /etc/snakeoil/molecule.lan/dh.pem

    raw: |
      if ($badagent) {
        return 403;
      }

  - name: 20-bar.molecule.lan
    state: present
    enabled: true

    domains:
      - bar.molecule.lan
      - ruf.molecule.lan
      - slo.molecule.lan
      - zup.molecule.lan

    # https://nginx.org/en/docs/http/ngx_http_core_module.html#listen
    listen:
      - 8443 reuseport
      - 443 ssl http2

    # enable ssl
    ssl:
      enabled: true
      ciphers: strong
      certificate:     /etc/snakeoil/molecule.lan/molecule.lan.pem
      certificate_key: /etc/snakeoil/molecule.lan/molecule.lan.key
      dhparam: /etc/snakeoil/molecule.lan/dh.pem

    raw: |
      if ($badagent) {
        return 403;
      }

      if ($host != bar.molecule.lan) {
        return 301 https://bar.molecule.lan$request_uri;
      }

  - name: 20-foo.docker.local
    filename: 20-foo.docker.local.conf
    state: absent
    enabled: true

    domains:
      - foo.docker.local

    listen: 80

    root:  /var/www/foo.docker.local

    logfiles:
      access:
        file: /var/log/nginx/foo.docker.local/access.log
        # loglevel: 'json_analytics'
      error:
        file: /var/log/nginx/foo.docker.local/error.log
        loglevel: notice

    # list of upstream servers
    upstreams:
      - name: paperless
        servers:
          - 127.0.0.1:8080   max_fails=3 fail_timeout=30s
        # strategy: 'ip_hash'
        keepalive: 32
      - name: unifi
        servers:
          - 127.0.0.1:8090   max_fails=3 fail_timeout=30s
        # strategy: 'ip_hash'
        keepalive: 32

    locations:
      "^~ /":
        options: |
          add_header X-Backend "bar";

          proxy_pass         http://paperless/;
          proxy_set_header   Host              $host;
          proxy_set_header   X-Real-IP         $remote_addr;
          proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Proto $scheme;

  - name: 40-foo.docker.local
    filename: 40-foo.docker.local.conf
    state: present
    enabled: false

    domains:
      - secure-foo.docker.local

    listen:
      - 443 ssl http2

    # enable ssl
    ssl:
      enabled: true
      ciphers: default
      certificate:     /etc/snakeoil/docker.local/docker.local.pem
      certificate_key: /etc/snakeoil/docker.local/docker.local.pem

  - name: 20-bar.docker.local
    state: present
    enabled: true

    domains:
      - bar.docker.local
      - docker.local

    # root_directory: /var/www/docker.local
    # root_directory_create: true

    acme_challenge: true

    redirects:
      - location: "/"
        return: 301
        destination: "https://$server_name$request_uri"

  - name: 40-bar.docker.local
    state: present
    enabled: true

    domains:
      - bar.docker.local
      - docker.local

    root_directory: /var/www/docker.local
    root_directory_create: true

    listen:
      - 443 ssl http2
      - 8443 reuseport

    logfiles:
      access:
        file: /var/log/nginx/bar.docker.local/access.log
        loglevel: 'json_combined'
      error:
        file: /var/log/nginx/bar.docker.local/error.log
        loglevel: warn

    # enable ssl
    ssl:
      enabled: true
      ciphers: default
      certificate:     /etc/snakeoil/docker.local/docker.local.pem
      certificate_key: /etc/snakeoil/docker.local/docker.local.key
      dhparam: /etc/snakeoil/docker.local/dh.pem

  - name: 25-git.matrix.lan
    description: |
      internal access to http://git.matrix.lan
    filename: 25-git.matrix.lan.conf

    domains:
      - git.matrix.lan

    listen:
      - 80

    upstreams:
      - name: git
        servers:
          - 192.168.0.135:3000

    logfiles:
      access:
        file: /var/log/nginx/git.matrix.lan/access.log
        loglevel: 'json_combined if=$excluded_ua'
      error:
        file: /var/log/nginx/git.matrix.lan/error.log
        loglevel: notice

    locations:
      "/":
        options: |
          add_header X-Backend "git";

          proxy_pass          http://git;
          proxy_http_version  1.1;
          proxy_set_header    Upgrade $http_upgrade;
          proxy_set_header    Connection "upgrade";

          proxy_set_header    Host              $host;
          proxy_set_header    X-Real-IP         $remote_addr;
          proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
          # proxy_set_header    X-Forwarded-Proto $scheme;

          proxy_redirect off;

  - name: 50-git.matrix.lan
    description: |
      internal access to http://git.matrix.lan
    filename: 50-git.matrix.lan.conf

    domains:
      - git.matrix.lan

    listen:
      - 443 ssl http2

    upstreams:
      - name: git
        servers:
          - 192.168.0.135:3000

    logfiles:
      access:
        file: /var/log/nginx/git.matrix.lan/access.log
        loglevel: 'json_combined if=$excluded_ua'
      error:
        file: /var/log/nginx/git.matrix.lan/error.log
        loglevel: notice

    # enable ssl
    ssl:
      enabled: true
      ciphers: default
      certificate: /etc/snakeoil/molecule.lan/molecule.lan.pem
      certificate_key: /etc/snakeoil/molecule.lan/molecule.lan.key
      dhparam: /etc/snakeoil/molecule.lan/dh.pem

    locations:
      "/":
        options: |
          add_header X-Backend "git";

          proxy_pass          http://git;
          proxy_http_version  1.1;
          proxy_set_header    Upgrade $http_upgrade;
          proxy_set_header    Connection "upgrade";

          proxy_set_header    Host              $host;
          proxy_set_header    X-Real-IP         $remote_addr;
          proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
          # proxy_set_header    X-Forwarded-Proto $scheme;

          proxy_redirect off;

...
