---

nginx_gzip:
  enabled: true

nginx_custom_includes:
  prometheus.conf: |
    # https://nginx.org/en/docs/http/ngx_http_core_module.html#satisfy
    satisfy any;
    # Die IP des HAProxy
    # damit ist es möglich das Jobs, die über den Jenkins aufgerufen werden und gegen
    # die admin URLs (https://admin.*.DOMAIN.TLD/admin/*) gehen
    # ohne Username/Passwort zu nutzen
    # Alle anderen Requests benötigen weiterhin die Authentifizierung via BA
    allow 192.168.0.0/24;
    deny  all;

    auth_basic           "Administrator’s Area";
    auth_basic_user_file "{{ htpasswd_credentials_path }}/.monitoring-passwdfile";

nginx_logformat:
  json_combined:
    format: |
      '{'
        '"time_local": "$time_local",'
        '"remote_addr": "$remote_addr",'
        '"remote_user": "$remote_user",'
        '"request": "$request",'
        '"status": "$status",'
        '"body_bytes_sent": "$body_bytes_sent",'
        '"request_time": "$request_time",'
        '"http_referrer": "$http_referer",'
        '"http_user_agent": "$http_user_agent"'
      '}';
    # escape: json

...
