---

- name: de-activated vhosts
  ansible.builtin.debug:
    msg: "{{ _deactivated_vhost }}"
  when:
    - _deactivated_vhost.changed

- name: removed vhost
  ansible.builtin.debug:
    msg: "{{ _removed_vhost }}"
  when:
    - _removed_vhost.changed

- name: validate config
  ansible.builtin.command: |
    nginx -t

- name: reload service
  ansible.builtin.service:
    name: nginx
    state: reloaded
#  command: |
#    [ -e /run/nxinx.pid ] && nginx -s reload

- name: restart service
  ansible.builtin.service:
    name: nginx
    state: restarted

...
