---

- name: de-activated vhosts  # noqa no-handler
  ansible.builtin.debug:
    msg: "{{ _deactivated_vhost }}"
  when:
    - _deactivated_vhost.changed

- name: removed vhost  # noqa no-handler
  ansible.builtin.debug:
    msg: "{{ _removed_vhost }}"
  when:
    - _removed_vhost.changed

- name: validate config  # noqa no-handler
  ansible.builtin.command: |
    nginx -t
  register: _validate
  changed_when: _validate.rc != 0
  failed_when: _validate.rc != 0

- name: reload service
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: restart service
  ansible.builtin.service:
    name: nginx
    state: restarted

...
