---

- name: syslog-ng
  src: bodsch.syslog_ng
  #src: https://github.com/bodsch/ansible-syslog-ng.git
  # scm: git
  version: 1.3.0

- name: htpasswd
  src: bodsch.htpasswd
  # src: https://github.com/bodsch/ansible-htpasswd.git
  version: 1.1.0

...
