---

nginx_vhosts:

  # HTTP
  # IPv6: false
  # ssl: false
  # LE: false
  default:
    ipv6: false
    # Set default site to return 444 (Connection Closed Without Response)
    # Set to True if you want to redirect http to https
    ssl: false
    letsencrypt: false

  # HTTP
  # enabled
  # present
  10-foo.molecule.lan_80:
    # state: absent
    # enabled: true
    # template: foo.tpl.j2
    domains:
      - foo.molecule.lan
    listen: 80

    root:  /var/www/foo.molecule.lan

    access_log: /var/log/nginx/bar.molecule.lan/access.log
    error_log: /var/log/nginx/bar.molecule.lan/error.log

    # creates an htpasswd file under
    # /etc/nginx/htpasswd.d/foo.molecule.lan
    htpasswd:
      - username: myusername_1
        password: mysecre
      - username: myusername_2
        password: mysecretpassword

    # list of upstream servers
    upstreams:
      - name: paperless
        servers:
          - 127.0.0.1:8080   max_fails=3 fail_timeout=30s
        # strategy: 'ip_hash'
        keepalive: 32
      - name: unifi
        servers:
          - 127.0.0.1:8090   max_fails=3 fail_timeout=30s
        # strategy: 'ip_hash'
        keepalive: 32


    locations:
      - location: "^~ /"
        options: |
          add_header X-Backend "bar";

          proxy_pass         http://paperless/;
          proxy_set_header   Host              $host;
          proxy_set_header   X-Real-IP         $remote_addr;
          proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Proto $scheme;

  # HTTP
  # enabled
  # present
  10-bar.molecule.lan_9000:
    domains:
      - bar.molecule.lan

    root:  /var/www/bar.molecule.lan

    # Specify which port you want to listen to with clear HTTP, or leave undefined for 80
    listen: 9000

  # HTTPS
  # enabled
  # absent
  # no letsencrypt
  # > 15-foo.molecule.lan.conf
  15-foo.molecule.lan_9080:
    filename: 15-foo.molecule.lan.conf
    domains:
      - foo.molecule.lan

    # state: absent

    # Specify which port you want to listen to with clear HTTP, or leave undefined for 80
    listen: 9080
    # Specify which port you want to listen to with HTTPS, or leave undefined for 443
    listen_ssl: 9081

    letsencrypt:
      enabled: false

    # enable ssl
    ssl: true
    ssl_certificate: /etc/ssl/certs/ssl-cert-snakeoil.pem
    ssl_certificate_key: /etc/ssl/private/ssl-cert-snakeoil.key

  # HTTPS
  # enabled
  # present
  # letsencrypt
  20-bar.molecule.lan:
    # state: absent
    # enabled: false
    domains:
      - bar.molecule.lan
      - ruf.molecule.lan
      - slo.molecule.lan
      - zup.molecule.lan

    listen: 443 http2

    letsencrypt:
      enabled: true
      email: "letsencrypt@test.com"

    # enable ssl
    ssl: true
    ssl_certificate:     /etc/letsencrypt/live/bar.molecule.lan/fullchain.pem
    ssl_certificate_key: /etc/letsencrypt/live/bar.molecule.lan/privkey.pem

  # HTTPS
  # enabled
  # present
  # no letsencrypt
  # > 20-foo.molecule.lan
  20-foo.molecule.lan:
    filename: 20-foo.molecule.lan.conf
    domains:
      - foo2.molecule.lan

    # Specify which port you want to listen to with clear HTTP, or leave undefined for 80
    listen: 9080
    # Specify which port you want to listen to with HTTPS, or leave undefined for 443
    listen_ssl: 9081

    letsencrypt:
      enabled: false
    # enable ssl
    ssl: true
    ssl_certificate: /etc/ssl/certs/ssl-cert-snakeoil.pem
    ssl_certificate_key: /etc/ssl/private/ssl-cert-snakeoil.key

  # HTTPS
  # enabled
  # present
  # letsencrypt
  # > 30-foofoo.molecule.lan
  30-foofoo.molecule.lan:
    filename: 30-foofoo.molecule.lan.conf
    # state: absent
    # enabled: false
    domains:
      - foo.molecule.lan

    listen: 443 http2

    letsencrypt:
      enabled: true
      email: "letsencrypt@test.com"

    # enable ssl
    ssl: true
    ssl_certificate:     /etc/letsencrypt/live/bar.molecule.lan/fullchain.pem
    ssl_certificate_key: /etc/letsencrypt/live/bar.molecule.lan/privkey.pem


nginx_vhosts_old:
  - server_name: "bar.molecule.lan"
    listen: 80
    state: present
    root:  /var/www/bar.molecule.lan
    access_log: /var/log/nginx/bar.molecule.lan/access.log
    error_log:  /var/log/nginx/bar.molecule.lan/error.log

    # Define this block for a single HTTP user/password, or leave undefined for unauthenticated vhosts
    htpasswd:
      - username: myusername_1
        password: mysecretpassword
      - username: myusername_2
        password: mysecretpassword

    extra_parameters: |
      location ^~ / {
        add_header X-Backend "bar";

        proxy_pass         http://paperless/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
      }
      # include modules.d/99-letsencrypt-acme-challenge.conf;

  - server_name: "foo.molecule.lan"
    listen: 80
    state: present
    root:  /var/www/foo.molecule.lan
    access_log: /var/log/nginx/foo.molecule.lan/access.log
    error_log:  /var/log/nginx/foo.molecule.lan/error.log

...
