---

- name: create includes.d/nginx_log.conf
  when:
    - not running_in_check_mode
  ansible.builtin.template:
    src: includes.d/nginx_log.conf.j2
    dest: /etc/nginx/includes.d/nginx_log.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - validate nginx config
    - reload nginx

...
