---

name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
        default: 'main'

defaults:
  run:
    working-directory: 'ansible-nginx'

env:
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  build-test:
    name: "${{ matrix.image }} | Ansible: ${{ matrix.ansible-version }}, Scenario: ${{ matrix.scenario }}"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - archlinux:latest
          - artixlinux:latest
        python_version:
          - "3.12"
        ansible-version:
          - '8.5'
        scenario:
          - default

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4
        with:
          path: 'ansible-nginx'
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: Force reinstall of community.docker
        run: |
          mkdir -p /home/runner/.ansible/collections
          ansible-galaxy collection install community.docker --force

      - name: Run tests
        run: |
          make \
            test \
            -e TOX_SCENARIO="${{ matrix.scenario }}" \
            -e TOX_ANSIBLE="ansible_${{ matrix.ansible-version }}" \
            -e DISTRIBUTION="${{ matrix.image }}"
