---

name: Configured Scenarios

on:
  workflow_run:
    workflows:
      - "Build & Test"
    types:
      - completed

defaults:
  run:
    working-directory: 'ansible-nginx'

env:
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  debian:
    name: "${{ matrix.scenario }} | ${{ matrix.image }}, Ansible ${{ matrix.ansible-version }}, Python ${{ matrix.python_version }}"
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:12
        python_version:
          - "3.12"
        ansible-version:
          - '9.5'
        scenario:
          - default
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'ansible-nginx'
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: 🐍 set up python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: force reinstall of community.docker
        run: |
          mkdir -p /home/runner/.ansible/collections
          ansible-galaxy collection install community.docker --force

      - name: test with tox
        run: |
          make \
            test \
            -e TOX_SCENARIO="${{ matrix.scenario }}" \
            -e TOX_ANSIBLE="ansible_${{ matrix.ansible-version }}" \
            -e DISTRIBUTION="${{ matrix.image }}"

  ubuntu:
    name: "${{ matrix.scenario }} | ${{ matrix.image }}, Ansible ${{ matrix.ansible-version }}, Python ${{ matrix.python_version }}"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu:22.04
          - ubuntu:24.04
        python_version:
          - "3.12"
        ansible-version:
          - '9.5'
        scenario:
          - default
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'ansible-nginx'
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: 🐍 set up python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: force reinstall of community.docker
        run: |
          mkdir -p /home/runner/.ansible/collections
          ansible-galaxy collection install community.docker --force

      - name: test with tox
        run: |
          make \
            test \
            -e TOX_SCENARIO="${{ matrix.scenario }}" \
            -e TOX_ANSIBLE="ansible_${{ matrix.ansible-version }}" \
            -e DISTRIBUTION="${{ matrix.image }}"

  scenarios:
    name: "${{ matrix.scenario }} | ${{ matrix.image }}, Ansible ${{ matrix.ansible-version }}, Python ${{ matrix.python_version }}"
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:12
        python_version:
          - "3.12"
        ansible-version:
          - '9.5'
        scenario:
          - configured
          - many-vhosts
          - with-syslog
          - support-geoip

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4
        with:
          path: 'ansible-nginx'
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: Force reinstall of community.docker
        run: |
          mkdir -p /home/runner/.ansible/collections
          ansible-galaxy collection install community.docker --force

      - name: Run tests
        run: |
          make \
            test \
            -e TOX_SCENARIO="${{ matrix.scenario }}" \
            -e TOX_ANSIBLE="ansible_${{ matrix.ansible-version }}" \
            -e DISTRIBUTION="${{ matrix.image }}"
