---
name: Code Linter

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  pycodestyle:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"

      - name: Install pycodestyle
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pycodestyle

      - name: Run pycodestyle
        run: |
          pycodestyle plugins/ --config=.config/pycodestyle.cfg --statistics --count --exclude=test_*.py,hooks/*.py

  flake8:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"

      - name: Install flake8
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8

      - name: Run flake8
        run: |
          flake8 --append-config=.config/pycodestyle.cfg
